<?xml version="1.0"?>
<robot
  xmlns:xacro="http://ros.org/wiki/xacro"
  xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
  xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
  xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
  name="acorn">



  <material name="grey">
    <color rgba="0.7 0 0 1"/>
  </material>

  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <!--New Include D435 realsense-->
  <!-- <xacro:include filename="$(find acorn_camera)/urdf/_d435.urdf.xacro" /> -->
  <!--New Include VLP-16-->
  <xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/>

  <xacro:include filename="$(find uos_common_urdf)/common.xacro" />
  <xacro:include filename="$(find uos_common_urdf)/urdf/imu.gazebo.urdf.xacro" />
  <xacro:include filename="$(find sick_tim)/urdf/sick_tim.urdf.xacro" />
  <xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro" />
  
  
  <xacro:property name="M_PI" value="3.14159265359"/>
  
  <xacro:property name="imu_stdev" value="0.00017" />
  <xacro:property name="body_height" value="0.2"/>
  <xacro:property name="body_length" value="0.48"/>
  <xacro:property name="body_width" value="0.32"/>
  
  <xacro:property name="axis_front" value="0.16"/>
  <xacro:property name="axis_back" value="-0.16"/>
  
  <xacro:property name="wheel_thickness" value="0.025"/>
  <xacro:property name="wheel_body_offset" value="${wheel_thickness/2 + 0.015}"/>
  <xacro:property name="wheel_radius" value="0.135"/>
  <xacro:property name="axis_height" value="-0.015"/>
  <xacro:property name="axis_right" value="-0.16"/>
  <xacro:property name="axis_left" value="0.16"/>
  <xacro:property name="axis_length" value="${body_width + 2 * wheel_body_offset}" />
  <xacro:property name="turning_adaptation" value="2.95" />

  <xacro:property name="laser_x" value="0.345"/>
  <xacro:property name="laser_z" value="0.035"/>

  <xacro:property name="body_mass" value="25.0"/>
  <xacro:property name="wheel_mass" value="5.0"/>

  <xacro:property name="imu_width" value="0.036"/>
  <xacro:property name="imu_length" value="0.038"/>
  <xacro:property name="imu_height" value="0.012"/>

  <xacro:property name="imu_offset_x" value="0"/>
  <xacro:property name="imu_offset_y" value="0"/>
  <xacro:property name="imu_offset_z" value="${- body_height/2 + 0.005 + 0.007}"/>

 
  <link name="base_footprint"/>
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
          <mesh filename="package://acorn_description/meshes/base_s.stl"/>
      </geometry>
      <material name="silver" >
        <color rgba="0.5 0.5 0.5 0.99" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertial
      x="${body_length}"
      y="${body_width}"
      z="${body_height}"
      mass="${body_mass}"/>
  </link>
  
  <joint name="base_footprint_to_base_joint" type="fixed">
    <origin xyz="0 0 ${wheel_radius - axis_height}" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>



<!--Attach Realsense D435 Camera to robot-->
  <!-- <xacro:sensor_d435
    suffix="front"
    parent="base_link">
    <origin xyz="0.09 0 0.1625" rpy="0 0 0" />
  </xacro:sensor_d435> -->

  <!--xacro:sensor_d435
    suffix="back"
    parent="base_link">
    <origin xyz="-0.325 0 0.085" rpy=" 0 0 ${M_PI}" />
  </xacro:sensor_d435-->

  <!--Attach VLP-16 to robot-->
  <xacro:VLP-16>
    <origin xyz="0 0 0.205"/>
  </xacro:VLP-16>

  <!--Wheel Macro-->
  <xacro:macro name="wheel" params="name parent xyz side">
    <link name="${name}_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://acorn_description/meshes/${side}_wheel_s.stl"/>
        </geometry>
        <material name="black" >
          <color rgba="0.2 0.2 0.2 0.99" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        <geometry>
          <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial
        radius="${wheel_radius}"
        length="${wheel_thickness}"
        mass="${wheel_mass}" />
    </link>

    <joint name="${name}_joint" type="continuous">
      <origin xyz="${xyz}" rpy="0 0 0"/>
      <parent link="${parent}"/>
      <child link="${name}_link"/>
      <axis xyz="0 1 0"/>
    </joint>

    <gazebo reference="${name}_link">
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
      <material>Gazebo/Black</material>
      <kp>100000.0</kp>
      <kd>10.0</kd>
      <fdir1>1 0 0</fdir1>
      <maxVel>1.0</maxVel>
      <minDepth>0.00</minDepth>
      <selfCollide>false</selfCollide>
    </gazebo>
  </xacro:macro>

  <xacro:wheel
    name="left_front_wheel"
    parent="base_link"
    xyz="${axis_front} ${axis_left} ${axis_height}"
    side="left"/>

  <xacro:wheel
    name="left_rear_wheel"
    parent="base_link"
    xyz="${axis_back} ${axis_left} ${axis_height}"
    side="left" />
  
  <xacro:wheel
    name="right_front_wheel"
    parent="base_link"
    xyz="${axis_front} ${axis_right} ${axis_height}"
    side="right" />
  
  <xacro:wheel
    name="right_rear_wheel"
    parent="base_link"
    xyz="${axis_back} ${axis_right} ${axis_height}"
    side="right" />
  
  <xacro:sick_tim551
    name="laser_front"
    ros_topic="/scan_front"
    min_angle="${-M_PI/2.0}"
    max_angle="${M_PI/2.0}" />

  <xacro:sick_tim551
    name="laser_back"
    ros_topic="/scan_back"
    min_angle="${-M_PI/2.0}"
    max_angle="${M_PI/2.0}" />

 
  <joint name="laser_front_base_joint" type="fixed">
    <parent link="base_link" />
    <child link="laser_front_mount_link" />
    <origin xyz="${laser_x} 0 ${laser_z}" rpy="${M_PI} 0 0"/>
  </joint>

  <joint name="laser_back_base_joint" type="fixed">
    <parent link="base_link" />
    <child link="laser_back_mount_link" />
    <origin xyz="-${laser_x} 0 ${laser_z}" rpy="${M_PI} 0 ${M_PI}"/>
  </joint>
  
  <link name="imu">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${imu_length} ${imu_width} ${imu_height}"/>
      </geometry>
      <material name="white" >
        <color rgba="0.8 0.8 0.8 1" />
      </material>
    </visual>
  </link>
  
  <joint name="imu_joint" type="fixed">
    <parent link="base_link" />
    <child link="imu" />
    <origin
      xyz=" ${imu_offset_x}
            ${imu_offset_y}
            ${imu_offset_z}"
      rpy="0 0 0" />
  </joint>

  <!-- inertial measurement unit for gazebo -->
  <xacro:imu_gazebo link="imu" imu_topic="imu/data" update_rate="100.0" stdev="${imu_stdev}" />

  <gazebo>

    <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
      <updateRate>200.0</updateRate>
      <robotNamespace>/</robotNamespace>
      <leftFrontJoint>left_front_wheel_joint</leftFrontJoint>
      <rightFrontJoint>right_front_wheel_joint</rightFrontJoint>
      <leftRearJoint>left_rear_wheel_joint</leftRearJoint>
      <rightRearJoint>right_rear_wheel_joint</rightRearJoint>
      <wheelSeparation>${axis_length}</wheelSeparation>
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <robotBaseFrame>base_link</robotBaseFrame>
      <torque>20</torque>
      <topicName>cmd_vel</topicName>
      <broadcastTF>false</broadcastTF>
    </plugin>
  </gazebo>

  <!-- publish ground truth for pose of base_footprint -->
  <gazebo>
    <plugin name="base_footprint_controller" filename="libgazebo_ros_p3d.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>30.0</updateRate>
      <bodyName>base_footprint</bodyName>
      <topicName>base_footprint_pose_ground_truth</topicName>
      <gaussianNoise>0.0</gaussianNoise>
      <frameName>map</frameName>
      <interface:position name="base_footprint_p3d_position_iface" />
    </plugin>
  </gazebo>

</robot>
